# Added to aide with eventual transition away from setup.py
[build-system]
requires = [
    "setuptools >= 35.0.2",
    "wheel",
    "setuptools_scm >= 2.0.0"
]
build-backend = "setuptools.build_meta"

[tool.trestle]
version = "1.0.0-rc.0"

[tool.semantic_release]
version_toml = "pyproject.toml:tool.trestle.version"
prerelease_tag = "rc"
branch = "v1.0.0-rc"
upload_to_pypi = "true"

[tool.pytest.ini_options]
minversion = "6.2"
testpaths = [
    "tests",
]
