name: Conventional PR for develop
on:
  pull_request:
    types: [opened, reopened, ready_for_review, edited]
    branches:
      - develop

jobs:
  hqprs:
    runs-on: ubuntu-latest
    steps:
      - name: conventional-pr
        uses: Namchee/conventional-pr@v0.4
        with:
          access_token: ${{ secrets.ADMIN_PAT }}
          check_draft: true
          link_issue: false
